# Generated by Django 2.2 on 2021-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=300)),
                ('timestamp', models.IntegerField()),
                ('miner', models.CharField(max_length=300)),
                ('number_of_transactions', models.IntegerField()),
            ],
        ),
    ]
